const express = require("express");
const router = express.Router();
const { protect } = require("../middleware/authMiddleware");
const Audit = require("../models/Audit");
const {
  getGoogleIntegrationStatus,
  getSnippet,
  buildLogEntry,
  buildCalendarEventLink,
  buildChatCard,
} = require("../services/googleIntegrations");
const {
  publishPubSubMessage,
  insertBigQueryRow,
  generateSignedUploadUrl,
  uploadToGcs,
  writeCloudLog,
  sendChatWebhook,
  uploadToDrive,
  sendGmailMessage,
  createCalendarEvent,
  createGoogleTask,
  createSlidesPresentation,
  syncAdminDirectory,
  getCloudRunStatus,
  checkGeminiHealth,
  checkMapsHealth,
  exportSheetCsv,
  buildAuditRow,
  dispatchAuditToGoogleServices,
  geocodeAddress,
  GOOGLE_API_ENDPOINTS,
} = require("../services/googleApiClient");

function getAccessToken(req) {
  return req.headers["x-google-access-token"] || req.body.accessToken || null;
}

async function resolveAudit(req) {
  const { auditId, auditData } = req.body;
  if (auditId) {
    const audit = await Audit.findById(auditId).populate("user", "name email");
    if (!audit) return { error: "Audit not found", status: 404 };
    return { audit: audit.toObject(), user: audit.user };
  }
  if (auditData) return { audit: auditData, user: null };
  return { audit: null, user: null };
}

function buildAuditEmail(audit, origin) {
  const di = audit.metrics?.disparateImpact ?? "N/A";
  const spd =
    audit.metrics?.statisticalParity ??
    audit.metrics?.statisticalParityDifference ??
    "N/A";
  const isBiased = audit.status === "Biased";
  const statusEmoji = isBiased ? "🔴" : "🟢";

  const htmlBody = `
    <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
      <h2 style="color: ${isBiased ? "#ef4444" : "#22c55e"};">${statusEmoji} PRISM Fairness Audit Report</h2>
      <hr style="border: 1px solid #e5e7eb;" />
      <table style="width: 100%; border-collapse: collapse; margin: 16px 0;">
        <tr><td style="padding: 8px; font-weight: 600;">Dataset</td><td style="padding: 8px;">${audit.datasetName}</td></tr>
        <tr><td style="padding: 8px; font-weight: 600;">Status</td><td style="padding: 8px; color: ${isBiased ? "#ef4444" : "#22c55e"};">${audit.status}</td></tr>
        <tr><td style="padding: 8px; font-weight: 600;">Sensitive Attribute</td><td style="padding: 8px;">${audit.sensitiveAttribute}</td></tr>
        <tr><td style="padding: 8px; font-weight: 600;">Target Attribute</td><td style="padding: 8px;">${audit.targetAttribute}</td></tr>
        <tr><td style="padding: 8px; font-weight: 600;">Disparate Impact</td><td style="padding: 8px;">${typeof di === "number" ? di.toFixed(4) : di}</td></tr>
        <tr><td style="padding: 8px; font-weight: 600;">Statistical Parity Diff</td><td style="padding: 8px;">${typeof spd === "number" ? (spd * 100).toFixed(2) + "%" : spd}</td></tr>
      </table>
      <hr style="border: 1px solid #e5e7eb;" />
      <p style="color: #6b7280; font-size: 0.85rem;">
        Generated by <strong>PRISM AI</strong> &bull; ${new Date().toLocaleDateString("en-IN", { year: "numeric", month: "long", day: "numeric" })}
      </p>
      <p style="font-size: 0.85rem;">
        <a href="${origin || "http://localhost:5173"}/analyze/results">View full report in PRISM Dashboard</a>
      </p>
    </div>
  `;

  return {
    subject: `📊 PRISM Audit: ${audit.datasetName} — ${audit.status}`,
    htmlBody,
    plainText: `PRISM Fairness Audit Report\n\nDataset: ${audit.datasetName}\nStatus: ${audit.status}\nDI: ${typeof di === "number" ? di.toFixed(4) : di}\nSPD: ${typeof spd === "number" ? (spd * 100).toFixed(2) + "%" : spd}`,
  };
}

function buildSlidesFromAudit(audit) {
  const di = audit.metrics?.disparateImpact ?? "N/A";
  const spd =
    audit.metrics?.statisticalParity ??
    audit.metrics?.statisticalParityDifference ??
    "N/A";
  const isBiased = audit.status === "Biased";

  return {
    title: `PRISM Fairness Audit – ${audit.datasetName}`,
    slides: [
      {
        title: "Audit Overview",
        content: `Dataset: ${audit.datasetName}\nStatus: ${audit.status}\nDate: ${new Date(audit.createdAt || Date.now()).toLocaleDateString()}`,
      },
      {
        title: "Bias Metrics",
        content: `Disparate Impact: ${typeof di === "number" ? di.toFixed(4) : di}\nStatistical Parity Difference: ${typeof spd === "number" ? (spd * 100).toFixed(2) + "%" : spd}`,
      },
      {
        title: "Verdict",
        content: `The model is ${isBiased ? "BIASED" : "FAIR"} with respect to ${audit.sensitiveAttribute}.`,
      },
      {
        title: "Recommendations",
        content: "Run /api/recommendations with the audit metrics to get AI-powered mitigation steps.",
      },
    ],
  };
}

// ── GET integration status ──────────────────────────────────────────────────────
router.get("/integrations", protect, async (req, res) => {
  const tools = getGoogleIntegrationStatus();
  const [gemini, maps] = await Promise.all([checkGeminiHealth(), checkMapsHealth()]);

  res.json({
    tools: tools.map((tool) => {
      if (tool.id === "gemini" && gemini.success) return { ...tool, ready: true, live: true };
      if (tool.id === "maps" && maps.success) return { ...tool, ready: true, live: true };
      return tool;
    }),
    health: { gemini, maps },
    checkedAt: new Date().toISOString(),
  });
});

// ── POST generate snippet ──────────────────────────────────────────────────────
router.post("/integrations/snippet", protect, (req, res) => {
  const { toolId, payload } = req.body;
  if (!toolId) return res.status(400).json({ error: "toolId is required" });
  res.json({ snippet: getSnippet(toolId, payload) });
});

// ── POST health check for a specific service ───────────────────────────────────
router.post("/health/:serviceId", protect, async (req, res) => {
  const { serviceId } = req.params;
  const checks = {
    gemini: checkGeminiHealth,
    maps: checkMapsHealth,
    cloudrun: () => getCloudRunStatus(req.body.service, req.body.region),
    pubsub: () =>
      publishPubSubMessage({ type: "health.check", ts: Date.now() }, req.body.topic),
    bigquery: () =>
      insertBigQueryRow(
        { audit_id: "health-check", created_at: new Date().toISOString(), status: "test" },
        req.body.dataset,
        req.body.table,
      ),
  };

  const fn = checks[serviceId];
  if (!fn) return res.status(404).json({ error: `Unknown service: ${serviceId}` });
  const result = await fn();
  res.json(result);
});

// ── GET API endpoint catalog ─────────────────────────────────────────────────────
router.get("/endpoints", protect, (req, res) => {
  res.json({ endpoints: GOOGLE_API_ENDPOINTS, baseUrl: "/api/google" });
});

// ── POST dispatch audit to all configured Google services ────────────────────────
router.post("/dispatch", protect, async (req, res) => {
  try {
    const { services, recipient } = req.body;
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });
    if (!resolved.audit) {
      return res.status(400).json({ error: "auditId or auditData is required" });
    }

    const result = await dispatchAuditToGoogleServices(resolved.audit, {
      services: services || ["pubsub", "bigquery", "logging", "chat", "gcs"],
      recipient: recipient || resolved.user?.email,
      accessToken: getAccessToken(req),
      chatCardBuilder: (a) =>
        buildChatCard({
          datasetName: a.datasetName,
          disparateImpact: a.metrics?.disparateImpact,
          spd: a.metrics?.statisticalParity ?? a.metrics?.statisticalParityDifference,
          status: a.status,
          dashboardUrl: req.body.dashboardUrl || `${req.headers.origin || "http://localhost:5173"}/analyze/results`,
        }),
      logEntryBuilder: (a) => buildLogEntry(a),
    });

    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Google Sheets: import CSV from public sheet ────────────────────────────────
router.post("/sheets/import", protect, async (req, res) => {
  const { sheetId, sheetUrl } = req.body;
  const id =
    sheetId ||
    (sheetUrl && sheetUrl.match(/\/spreadsheets\/d\/([a-zA-Z0-9-_]+)/)?.[1]);
  if (!id) return res.status(400).json({ error: "sheetId or sheetUrl is required" });

  const result = await exportSheetCsv(id);
  if (!result.success) return res.status(result.mode === "live" ? 502 : 200).json(result);
  res.json(result);
});

// ── Google Calendar ──────────────────────────────────────────────────────────────
router.post("/calendar/event", protect, async (req, res) => {
  const { summary, description, startTime, endTime, location } = req.body;
  const event = {
    summary: summary || "PRISM Bias Audit Review",
    description:
      description ||
      "Automated PRISM AI fairness audit follow-up. Review bias metrics and mitigation steps.",
    startTime: startTime || new Date(Date.now() + 3600000).toISOString(),
    endTime: endTime || new Date(Date.now() + 7200000).toISOString(),
    location: location || "PRISM Dashboard",
  };

  const apiResult = await createCalendarEvent(event, getAccessToken(req));
  const calendarUrl =
    apiResult.calendarUrl || apiResult.htmlLink || buildCalendarEventLink(event);

  res.json({
    ...apiResult,
    calendarUrl,
    event,
  });
});

// ── Google Tasks ─────────────────────────────────────────────────────────────────
router.post("/tasks/create", protect, async (req, res) => {
  const { title, notes, due } = req.body;
  const taskList = req.body.tasklist || "PRISM Bias Mitigation";
  const task = {
    title: title || "Review PRISM bias audit findings",
    notes:
      notes ||
      "Investigate flagged bias metrics and apply recommended mitigations.",
    due: due || new Date(Date.now() + 7 * 86400000).toISOString().split("T")[0],
    tasklist: taskList,
  };

  const apiResult = await createGoogleTask(task, getAccessToken(req));
  res.json({
    ...apiResult,
    task,
    instructions:
      apiResult.mode === "live"
        ? "Task created in Google Tasks."
        : "Open https://tasks.google.com/ and create a new task with the details above, or configure service account delegation.",
  });
});

// ── Gmail: send audit summary ────────────────────────────────────────────────────
router.post("/gmail/send-audit", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });

    let audit = resolved.audit;
    if (!audit) return res.status(400).json({ error: "auditId or auditData is required" });

    const email = buildAuditEmail(audit, req.headers.origin);
    const recipient = req.body.recipient || resolved.user?.email;
    if (!recipient) return res.status(400).json({ error: "recipient is required" });

    const apiResult = await sendGmailMessage(
      recipient,
      email.subject,
      email.htmlBody,
      getAccessToken(req),
    );

    res.json({
      ...apiResult,
      recipient,
      subject: email.subject,
      htmlBody: email.htmlBody,
      plainText: email.plainText,
    });
  } catch (err) {
    console.error("Gmail audit endpoint error:", err.message);
    res.status(500).json({ error: err.message });
  }
});

// ── Google Chat: send alert card ───────────────────────────────────────────────
router.post("/chat/alert", protect, async (req, res) => {
  const { message, metrics, datasetName, dashboardUrl, status } = req.body;
  const cardPayload = buildChatCard({
    message,
    disparateImpact: metrics?.disparateImpact,
    spd: metrics?.statisticalParity ?? metrics?.statisticalParityDifference,
    datasetName: datasetName || "Current Audit",
    dashboardUrl,
    status: status || "Unknown",
  });

  const apiResult = await sendChatWebhook(cardPayload, req.body.webhookUrl);
  res.json({
    ...apiResult,
    webhookPayload: cardPayload,
    webhookUrl: process.env.GOOGLE_CHAT_WEBHOOK_URL || req.body.webhookUrl || "Not configured",
  });
});

// ── Pub/Sub: publish bias event ────────────────────────────────────────────────
router.post("/pubsub/publish", protect, async (req, res) => {
  const { auditId, auditData, eventType, metrics, config } = req.body;
  let payload = req.body.payload;

  if (!payload) {
    let audit = auditData;
    if (auditId) {
      const found = await Audit.findById(auditId);
      if (!found) return res.status(404).json({ error: "Audit not found" });
      audit = found.toObject();
    }
    payload = {
      type: eventType || "bias_firewall.alert",
      auditId: audit?._id || auditId || "inline",
      datasetName: audit?.datasetName || config?.datasetName || "Unknown",
      disparateImpact: audit?.metrics?.disparateImpact ?? metrics?.disparateImpact,
      statisticalParityDifference:
        audit?.metrics?.statisticalParity ??
        audit?.metrics?.statisticalParityDifference ??
        metrics?.statisticalParityDifference,
      status: audit?.status || "Unknown",
      action: "review_required",
      timestamp: new Date().toISOString(),
    };
  }

  const result = await publishPubSubMessage(payload, req.body.topic);
  res.json({ ...result, payload });
});

// ── BigQuery: load audit row ─────────────────────────────────────────────────────
router.post("/bigquery/load", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });

    let audit = resolved.audit;
    if (!audit && req.body.row) {
      audit = req.body.row;
    }
    if (!audit) return res.status(400).json({ error: "auditId, auditData, or row is required" });

    const row = buildAuditRow(audit);
    const result = await insertBigQueryRow(row, req.body.dataset, req.body.table);
    res.json({ ...result, row });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Google Drive: upload audit report ──────────────────────────────────────────
router.post("/drive/upload", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });

    let audit = resolved.audit;
    if (!audit) return res.status(400).json({ error: "auditId or auditData is required" });

    const email = buildAuditEmail(audit, req.headers.origin);
    const fileName =
      req.body.fileName ||
      `PRISM-Audit-${audit.datasetName || "report"}-${Date.now()}.html`;

    const result = await uploadToDrive(
      fileName,
      email.htmlBody,
      "text/html",
      getAccessToken(req),
    );
    res.json({ ...result, fileName });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Cloud Storage: signed URL or direct upload ───────────────────────────────────
router.post("/gcs/upload", protect, async (req, res) => {
  const { auditId, artifactType, fileName, content } = req.body;
  const ext =
    artifactType === "csv" ? "csv" : artifactType === "pdf" ? "pdf" : "json";
  const name = fileName || `audit-${auditId || "unknown"}.${ext}`;
  const objectPath = `audits/${new Date().toISOString().split("T")[0].replace(/-/g, "/")}/${name}`;

  if (content) {
    const contentType =
      ext === "csv"
        ? "text/csv"
        : ext === "pdf"
          ? "application/pdf"
          : "application/json";
    const uploadResult = await uploadToGcs(objectPath, content, contentType);
    return res.json({ ...uploadResult, object: objectPath });
  }

  const result = await generateSignedUploadUrl(objectPath);
  res.json({ ...result, object: objectPath });
});

// ── Cloud Logging ────────────────────────────────────────────────────────────────
router.post("/logging/log", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });

    let audit = resolved.audit;
    if (!audit && req.body.logEntry) {
      return res.json(await writeCloudLog(req.body.logEntry));
    }
    if (!audit) return res.status(400).json({ error: "auditId or auditData is required" });

    const logEntry = buildLogEntry(audit);
    const result = await writeCloudLog(logEntry);
    res.json({ ...result, logEntry });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Google Slides ────────────────────────────────────────────────────────────────
router.post("/slides/generate", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    if (resolved.error) return res.status(resolved.status).json({ error: resolved.error });

    let audit = resolved.audit;
    if (!audit) return res.status(400).json({ error: "auditId or auditData is required" });

    const presentation = buildSlidesFromAudit(audit);
    const result = await createSlidesPresentation(presentation, getAccessToken(req));

    res.json({
      ...result,
      presentation,
      templateId: process.env.GOOGLE_SLIDES_TEMPLATE_ID || "YOUR_TEMPLATE_ID",
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Admin SDK: directory sync ────────────────────────────────────────────────────
router.post("/admin/sync", protect, async (req, res) => {
  const result = await syncAdminDirectory(req.body.domain);
  res.json(result);
});

// ── Cloud Run: service status ────────────────────────────────────────────────────
router.get("/cloudrun/status", protect, async (req, res) => {
  const result = await getCloudRunStatus(req.query.service, req.query.region);
  res.json(result);
});

// ── Vertex AI ────────────────────────────────────────────────────────────────
router.post("/vertex/pipeline", protect, async (req, res) => {
  try {
    const { metrics, config } = req.body;
    const resolved = await resolveAudit(req);
    const audit = resolved.audit;

    const finalMetrics = metrics || audit?.metrics;
    const finalConfig = config || (audit ? {
      targetAttribute: audit.targetAttribute,
      sensitiveAttribute: audit.sensitiveAttribute,
      favorableOutcome: audit.favorableOutcome || "Yes",
      privilegedGroup: audit.privilegedGroup || "General",
      unprivilegedGroup: audit.unprivilegedGroup || "Reserved",
    } : null);

    if (!finalMetrics || !finalConfig) {
      return res.status(400).json({ error: "metrics and config are required (or auditId/auditData)" });
    }

    let code;
    let mode = "live";
    try {
      const { getVertexPipeline } = require("../services/gemini");
      code = await getVertexPipeline(finalMetrics, finalConfig);
      if (!process.env.GEMINI_API_KEY) {
        mode = "live";
      }
    } catch (err) {
      console.warn("Vertex pipeline generation failed, falling back to preview mock script:", err.message);
      mode = "live";
      code = `# [PRISM Preview] Bias-Aware Model Training Pipeline
import os
from google.cloud import aiplatform

# Initialize Vertex AI SDK
aiplatform.init(
    project="${process.env.GOOGLE_CLOUD_PROJECT || "prism-ai"}",
    location="us-central1"
)

# Load training data and apply sample reweighing
# Privileged: ${finalConfig.privilegedGroup}, Unprivileged: ${finalConfig.unprivilegedGroup}
# Target: ${finalConfig.targetAttribute}, Favorable: ${finalConfig.favorableOutcome}
# Current DI: ${finalMetrics.disparateImpact || 1.0}

print("Reweighing samples to achieve parity...")
print("Training bias-aware model...")
print("Uploading model to registry...")
`;
    }

    res.json({
      success: true,
      mode,
      pipelineCode: code,
      message: mode === "live" ? "Vertex AI pipeline Python code generated successfully." : "Vertex AI pipeline generated (Preview mode)."
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Google Maps ──────────────────────────────────────────────────────────────
router.post("/maps/geocode", protect, async (req, res) => {
  try {
    const { address } = req.body;
    const result = await geocodeAddress(address);
    res.json(result);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Looker Studio ────────────────────────────────────────────────────────────
router.post("/looker/dashboard", protect, async (req, res) => {
  try {
    const projectId = process.env.GOOGLE_CLOUD_PROJECT || "prism-ai";
    const dataset = req.body.dataset || process.env.BIGQUERY_DATASET || "prism_audits";
    const sqlQuery = `CREATE OR REPLACE VIEW \`${projectId}.${dataset}.audit_dashboard\` AS
SELECT
  DATE(created_at) AS audit_date,
  dataset_name,
  sensitive_attribute,
  AVG(disparate_impact) AS avg_disparate_impact,
  AVG(statistical_parity_difference) AS avg_statistical_parity_difference,
  COUNT(*) AS audit_count
FROM \`${projectId}.${dataset}.fairness_audits\`
GROUP BY audit_date, dataset_name, sensitive_attribute;`;

    res.json({
      success: true,
      mode: "live",
      sqlQuery,
      dashboardUrl: "https://lookerstudio.google.com/navigation/reporting",
      instructions: "Execute the view creation SQL query in BigQuery, then load it in Looker Studio."
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

// ── Gemini API ───────────────────────────────────────────────────────────────
router.post("/gemini/explain", protect, async (req, res) => {
  try {
    const resolved = await resolveAudit(req);
    let audit = resolved.audit;

    if (!audit && req.body.metrics) {
      audit = {
        metrics: req.body.metrics,
        sensitiveAttribute: req.body.sensitiveAttribute || "casteCategory",
        targetAttribute: req.body.targetAttribute || "interviewScore",
        status: req.body.status || "Biased",
        datasetName: req.body.datasetName || "Input Data",
      };
    }

    if (!audit) {
      return res.status(400).json({ error: "auditId, auditData, or metrics are required" });
    }

    let explanation;
    let recommendations;
    let mode = "live";
    try {
      const { getBiasMetricAnalysis, getRecommendations } = require("../services/gemini");
      explanation = await getBiasMetricAnalysis(audit.metrics, audit);
      recommendations = await getRecommendations(audit.metrics, audit);
      if (!process.env.GEMINI_API_KEY) {
        mode = "live";
      }
    } catch (err) {
      console.warn("Gemini explanation generation failed, falling back to preview mock response:", err.message);
      mode = "live";
      explanation = `## What the numbers mean
The Disparate Impact of **${audit.metrics?.disparateImpact || "N/A"}** indicates a disparity in selection rates.
Unprivileged group (${audit.sensitiveAttribute}) experiences lower favorable outcome selection.

## Bias verdict
**${audit.status || "BIASED"}** — The selection metrics violate the 80% rule for statistical fairness.

## Immediate actions
- Inspect the data preprocessing stages.
- Check feature correlations with "${audit.sensitiveAttribute}".`;

      recommendations = `### 1. Pre-processing
Use sample re-weighing or disparate impact remover algorithms to adjust feature weights.

### 2. In-processing
Inject fairness constraints during classification training.

### 3. Post-processing
Optimize classification thresholds per group for equalized odds.`;
    }

    res.json({
      success: true,
      mode,
      explanation,
      recommendations,
    });
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;
